import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { BookstoreThemeWrapper, NavbarStyled } from "@/components/BookstoreTheme";
import { Toaster } from "@/components/ui/toast/toaster";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Bookverse",
  description: "Generated by CodeezaDevs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <BookstoreThemeWrapper>
              <NavbarStyled>
                {/* Add your navbar content here */}
              </NavbarStyled>
              <main className="max-w-7xl mx-auto p-6">
                {children}
              </main>
              <Toaster />
            </BookstoreThemeWrapper>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
